### ISSUE TITLE
remember the last selected devices?

### ISSUE THREAD

**Issue by tizi24** [jazz-soft/JZZ-gui-Select#2]
Is there any way that I can save the input and output midi devices so I don't have to select again?

**Comment by jazz-soft** [comment]
You can save the name in the `onSelect()` handler and use it in the `select()` function later.

**Comment by tizi24** [comment]
perfect! This orientation helped me a lot to be able to do it, THANK YOU!

**Comment by jazz-soft** [comment]
You are welcome! :)
